stages:
  - deploy

deploy-job:
  stage: deploy
  before_script:
    - chmod 600 $SSH_PRIVATE_KEY
  script:
    - >
      ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY -p 3031 easybitpay@138.201.35.101 "
      cd /home/easybitpay/v4/front &&
      git pull origin main &&
      npm install &&
      bash /home/easybitpay/v4/front/build.sh"